[tool.poetry]
name = "raindrop-information-extaction"
version = "0.1.0"
description = ""
authors = ["dorschre <renedorsch@yahoo.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
raindrop-io-py = "^0.4.1"
python-slugify = "^8.0.4"
keybert = "^0.8.5"
openai = "^1.53.0"
markdownify = "^0.13.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
